console.log(typeof 15); // Output: "number"
console.log(typeof 42.7); // Output: "number"
console.log(typeof 5.5e-6); // Output: "number"
console.log(typeof Infinity); // Output: "number"
console.log(typeof NaN); // Output: "number". Despite being "Not-A-Number"